version: "3.9"

services:
  product-service:
    build: ./microservices/product-service
    container_name: product-service
    ports:
      - "5001:5001"
    networks:
      - ecommerce-net

  cart-service:
    build: ./microservices/cart-service
    container_name: cart-service
    ports:
      - "5002:5002"
    networks:
      - ecommerce-net
    depends_on:
      - product-service

  order-service:
    build: ./microservices/order-service
    container_name: order-service
    ports:
      - "5003:5003"
    networks:
      - ecommerce-net
    depends_on:
      - cart-service

  payment-service:
    build: ./microservices/payment-service
    container_name: payment-service
    ports:
      - "5004:5004"
    networks:
      - ecommerce-net
    depends_on:
      - order-service

networks:
  ecommerce-net:
    driver: bridge
