pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "product-service"
        DOCKER_USER = credentials('dockerhub-username')   // Jenkins credentials ID
        DOCKER_PASS = credentials('dockerhub-password')   // Jenkins credentials ID
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/<your-github-username>/ecommerce-microservices-devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE}:latest ./microservices/product-service"
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                script {
                    sh "echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin"
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    sh "docker tag ${DOCKER_IMAGE}:latest ${DOCKER_USER}/${DOCKER_IMAGE}:latest"
                    sh "docker push ${DOCKER_USER}/${DOCKER_IMAGE}:latest"
                }
            }
        }
    }
}
